return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  lazy = false,
  branch = 'main',
  config = function()
    local parsers = {
      'bash',
      'c',
      'css',
      'dockerfile',
      'git_config',
      'git_rebase',
      'gitcommit',
      'go',
      'gomod',
      'gosum',
      'gotmpl',
      'gowork',
      'html',
      'javascript',
      'json',
      'jsonnet',
      'jsx',
      'lua',
      'make',
      'markdown',
      'nix',
      'python',
      'rust',
      'ssh_config',
      'starlark',
      'terraform',
      'toml',
      'tsx',
      'typescript',
      'vim',
      'vimdoc',
      'yaml',
    }
    vim.api.nvim_create_autocmd('FileType', {
      pattern = parsers,
      callback = function() vim.treesitter.start() end,
    })
    require('nvim-treesitter').install(parsers)
  end,
}
